export const secteurs = [
  {
    slug: 'agriculture-foresterie',
    title: 'Agriculture et Foresterie',
    icon: '🌱',
    color: 'from-green-400 to-emerald-600',
    colorPale: 'from-green-50 to-emerald-50',
    iconColor: 'text-green-600',
    tag: 'GlobalGAP · ISO 22000',
    description:
      "CERTIZEN accompagne les acteurs agricoles et forestiers dans la mise en place de systèmes de management garantissant la sécurité des produits, la traçabilité et le respect des bonnes pratiques agricoles. Notre expertise couvre l'ensemble de la chaîne de valeur agricole, des semences jusqu'à la distribution.",
    descriptionLong: [
      "Le secteur agricole est soumis à des exigences croissantes en matière de traçabilité, de sécurité sanitaire et de durabilité environnementale. Les acheteurs internationaux, les grandes surfaces et les réglementations européennes imposent des standards de plus en plus stricts.",
      "CERTIZEN vous aide à structurer votre système de management agricole pour répondre à ces exigences, accéder aux marchés d'exportation et valoriser votre démarche qualité auprès de vos clients.",
    ],
    certifications: ['GlobalGAP', 'ISO 22000', 'Bio certification', 'HACCP', 'UTZ / Rainforest'],
    avantages: [
      "Amélioration de la traçabilité des produits agricoles",
      "Conformité aux exigences des grandes surfaces nationales et internationales",
      "Accès facilité aux marchés d'exportation (UE, USA, Golfe)",
      "Réduction des risques sanitaires et phytosanitaires",
      "Valorisation de votre image auprès des consommateurs",
    ],
    process: [
      { step: '01', title: 'Diagnostic initial', desc: 'Évaluation de vos pratiques actuelles et identification des écarts par rapport aux référentiels ciblés.' },
      { step: '02', title: 'Plan d\'action', desc: 'Élaboration d\'un programme de mise en conformité adapté à votre exploitation.' },
      { step: '03', title: 'Formation', desc: 'Sensibilisation et formation de votre personnel aux bonnes pratiques agricoles.' },
      { step: '04', title: 'Certification', desc: 'Accompagnement lors de l\'audit de certification et suivi post-certification.' },
    ],
  },
  {
    slug: 'batiments-infrastructures',
    title: 'Bâtiments et Infrastructures',
    icon: '🏗️',
    color: 'from-slate-500 to-gray-700',
    colorPale: 'from-slate-50 to-gray-50',
    iconColor: 'text-slate-600',
    tag: 'ISO 9001 · ISO 45001',
    description:
      "Nous aidons les entreprises du BTP à structurer leur système qualité et sécurité, à réduire les accidents du travail et à répondre aux exigences des donneurs d'ordre publics et privés. Une certification reconnue pour gagner des marchés.",
    descriptionLong: [
      "Le secteur du bâtiment et des infrastructures est confronté à des défis majeurs : sécurité des chantiers, délais, qualité des ouvrages et conformité réglementaire. Les donneurs d'ordre exigent de plus en plus des entreprises certifiées.",
      "CERTIZEN déploie des systèmes de management intégrés Qualité-Sécurité-Environnement (QSE) qui vous permettent de vous différencier sur les appels d'offres et d'améliorer vos performances opérationnelles.",
    ],
    certifications: ['ISO 9001', 'ISO 45001', 'ISO 14001', 'MASE', 'CEFRI'],
    avantages: [
      "Réduction significative des accidents et incidents sur chantier",
      "Accès aux marchés publics et grands projets privés",
      "Amélioration de la satisfaction client et réduction des réclamations",
      "Optimisation des processus de construction et réduction des coûts",
      "Image professionnelle renforcée auprès des maîtres d'ouvrage",
    ],
    process: [
      { step: '01', title: 'Audit de situation', desc: 'Analyse de vos pratiques actuelles et identification des risques prioritaires.' },
      { step: '02', title: 'Mise en conformité', desc: 'Structuration de vos procédures et documentation selon les exigences ISO.' },
      { step: '03', title: 'Formation équipes', desc: 'Sensibilisation du personnel de chantier et de bureau aux nouvelles procédures.' },
      { step: '04', title: 'Audit & Certification', desc: 'Préparation et accompagnement lors de l\'audit de certification externe.' },
    ],
  },
  {
    slug: 'biens-consommation-retail',
    title: 'Biens de consommation & Vente au détail',
    icon: '🛍️',
    color: 'from-pink-400 to-rose-600',
    colorPale: 'from-pink-50 to-rose-50',
    iconColor: 'text-rose-500',
    tag: 'ISO 9001 · BRCGS · IFS',
    description:
      "Pour les distributeurs et fabricants de biens de consommation, CERTIZEN déploie des référentiels reconnus par la grande distribution mondiale, garantissant qualité, sécurité et conformité des produits sur tous les marchés.",
    descriptionLong: [
      "La grande distribution impose des exigences croissantes à ses fournisseurs. BRCGS et IFS sont devenus incontournables pour accéder aux rayons des enseignes nationales et internationales.",
      "CERTIZEN vous accompagne depuis l'évaluation initiale jusqu'à l'obtention de votre certification, avec un suivi personnalisé adapté à votre activité.",
    ],
    certifications: ['BRCGS Consumer Products', 'ISO 9001', 'IFS HPC', 'SA8000', 'ISO 26000'],
    avantages: [
      "Référencement chez les grandes enseignes de distribution",
      "Renforcement de la confiance des consommateurs et partenaires",
      "Maîtrise des risques produits et réduction des rappels",
      "Amélioration de la compétitivité et de la valeur perçue",
      "Conformité aux réglementations des marchés cibles",
    ],
    process: [
      { step: '01', title: 'Analyse des écarts', desc: 'Évaluation de votre conformité actuelle aux référentiels BRCGS / IFS.' },
      { step: '02', title: 'Plan de mise à niveau', desc: 'Programme d\'actions correctives et préventives priorisées.' },
      { step: '03', title: 'Déploiement', desc: 'Mise en œuvre des procédures et systèmes de contrôle qualité.' },
      { step: '04', title: 'Certification', desc: 'Accompagnement lors de l\'audit de certification.' },
    ],
  },
  {
    slug: 'cosmetique-hygiene',
    title: 'Cosmétique & Hygiène',
    icon: '✨',
    color: 'from-purple-400 to-violet-600',
    colorPale: 'from-purple-50 to-violet-50',
    iconColor: 'text-violet-500',
    tag: 'ISO 22716 · GMP · BPF',
    description:
      "Le secteur cosmétique exige une maîtrise rigoureuse des formulations et de l'hygiène. CERTIZEN accompagne les fabricants dans la mise en conformité aux Bonnes Pratiques de Fabrication (BPF/GMP) et la norme ISO 22716.",
    descriptionLong: [
      "L'industrie cosmétique est soumise à des réglementations strictes en Europe, aux États-Unis et dans les pays du Golfe. La norme ISO 22716 (GMP Cosmétiques) est devenue un prérequis pour l'exportation.",
      "CERTIZEN vous aide à structurer votre système qualité, valider vos formulations et obtenir les certifications nécessaires à votre développement commercial international.",
    ],
    certifications: ['ISO 22716', 'GMP Cosmétiques', 'ISO 9001', 'Ecocert / COSMOS', 'Halal Cosmétiques'],
    avantages: [
      "Conformité réglementaire européenne (Règlement CE 1223/2009) et internationale",
      "Contrôle qualité rigoureux des matières premières et produits finis",
      "Sécurité et innocuité des formulations garanties",
      "Accès aux marchés export (UE, USA, pays du Golfe)",
      "Valorisation de votre démarche qualité auprès des distributeurs",
    ],
    process: [
      { step: '01', title: 'Audit BPF', desc: 'Évaluation de vos installations et pratiques de fabrication.' },
      { step: '02', title: 'Plan de conformité', desc: 'Identification et correction des non-conformités prioritaires.' },
      { step: '03', title: 'Documentation', desc: 'Mise en place des procédures, fiches techniques et enregistrements.' },
      { step: '04', title: 'Certification', desc: 'Accompagnement lors de l\'audit de certification ISO 22716.' },
    ],
  },
  {
    slug: 'cybersecurite-technologie',
    title: 'Cybersécurité et Technologie',
    icon: '🛡️',
    color: 'from-blue-400 to-cyan-600',
    colorPale: 'from-blue-50 to-cyan-50',
    iconColor: 'text-blue-600',
    tag: 'ISO 27001 · SOC 2 · RGPD',
    description:
      "Dans un monde de plus en plus numérique, CERTIZEN aide les entreprises tech à protéger leurs actifs informationnels, sécuriser leurs données et se conformer aux exigences de la norme ISO 27001.",
    descriptionLong: [
      "Les cyberattaques sont en constante augmentation et les réglementations sur la protection des données se renforcent (RGPD, NIS2). La certification ISO 27001 est devenue un standard de confiance reconnu mondialement.",
      "CERTIZEN vous accompagne dans la mise en place de votre Système de Management de la Sécurité de l'Information (SMSI), de l'analyse des risques jusqu'à la certification.",
    ],
    certifications: ['ISO 27001', 'ISO 27701', 'SOC 2 Type II', 'RGPD / DPO', 'NIS2'],
    avantages: [
      "Protection des données sensibles de l'entreprise et des clients",
      "Conformité RGPD et réglementations locales sur la protection des données",
      "Renforcement de la confiance des partenaires et clients",
      "Réduction du risque de cyberattaques et de violations de données",
      "Avantage compétitif sur les appels d'offres exigeant ISO 27001",
    ],
    process: [
      { step: '01', title: 'Analyse des risques', desc: 'Identification et évaluation des risques liés à la sécurité de l\'information.' },
      { step: '02', title: 'Politique SMSI', desc: 'Définition du périmètre et des politiques de sécurité.' },
      { step: '03', title: 'Contrôles & mesures', desc: 'Mise en place des 93 contrôles de l\'Annexe A d\'ISO 27001.' },
      { step: '04', title: 'Certification', desc: 'Audit de certification par un organisme accrédité.' },
    ],
  },
  {
    slug: 'environnement-sante-securite',
    title: 'Environnement, Santé & Sécurité',
    icon: '🍃',
    color: 'from-teal-400 to-green-600',
    colorPale: 'from-teal-50 to-green-50',
    iconColor: 'text-teal-600',
    tag: 'ISO 14001 · ISO 45001 · QHSE',
    description:
      "CERTIZEN accompagne les entreprises dans l'intégration d'un système de management HSE performant, réduisant l'impact environnemental et garantissant la sécurité des collaborateurs.",
    descriptionLong: [
      "La responsabilité environnementale et la sécurité au travail sont au cœur des préoccupations des entreprises modernes. ISO 14001 et ISO 45001 offrent un cadre structuré pour gérer ces enjeux.",
      "CERTIZEN déploie des systèmes de management HSE intégrés qui s'appuient sur votre culture d'entreprise et vos contraintes opérationnelles, pour un résultat concret et durable.",
    ],
    certifications: ['ISO 14001', 'ISO 45001', 'EMAS', 'ISO 50001', 'MASE'],
    avantages: [
      "Réduction mesurable de l'empreinte environnementale",
      "Conformité aux réglementations HSE nationales et internationales",
      "Diminution significative des accidents du travail et maladies professionnelles",
      "Image d'entreprise responsable et durable",
      "Réduction des coûts liés aux incidents et non-conformités",
    ],
    process: [
      { step: '01', title: 'Analyse environnementale', desc: 'Identification des aspects environnementaux et dangers liés au travail.' },
      { step: '02', title: 'Programme HSE', desc: 'Définition des objectifs et programmes de management.' },
      { step: '03', title: 'Formation & sensibilisation', desc: 'Formation du personnel à la culture HSE.' },
      { step: '04', title: 'Audit & certification', desc: 'Préparation et obtention de la certification ISO 14001 / ISO 45001.' },
    ],
  },
  {
    slug: 'alimentaire',
    title: 'Alimentaire',
    icon: '🍽️',
    color: 'from-orange-400 to-amber-600',
    colorPale: 'from-orange-50 to-amber-50',
    iconColor: 'text-orange-500',
    tag: 'ISO 22000 · HACCP · IFS · BRCGS · FSSC 22000',
    description:
      "C'est le cœur de l'expertise CERTIZEN. Nous accompagnons toute la filière alimentaire — de la production à la distribution — dans la mise en place de systèmes robustes de sécurité des aliments, reconnus mondialement.",
    descriptionLong: [
      "La sécurité alimentaire est une priorité absolue pour les consommateurs, les distributeurs et les régulateurs. ISO 22000, HACCP, BRCGS et IFS sont les référentiels incontournables du secteur.",
      "CERTIZEN possède une expertise terrain unique dans l'accompagnement des entreprises alimentaires : abattoirs, transformateurs, conserveries, meuneries, boulangeries industrielles, et bien d'autres.",
    ],
    certifications: ['ISO 22000', 'HACCP', 'IFS Food', 'BRCGS Food', 'FSSC 22000', 'Halal / Casher'],
    avantages: [
      "Maîtrise totale des risques alimentaires tout au long de la chaîne",
      "Certification reconnue par les distributeurs mondiaux",
      "Accès aux marchés européens, américains et du Golfe",
      "Conformité réglementaire complète (CE, FDA, EFSA)",
      "Réduction des rappels produits et crises alimentaires",
    ],
    process: [
      { step: '01', title: 'Analyse des dangers', desc: 'Identification et évaluation de tous les dangers biologiques, chimiques et physiques.' },
      { step: '02', title: 'Plan HACCP', desc: 'Définition des CCP, limites critiques et procédures de surveillance.' },
      { step: '03', title: 'Système de management', desc: 'Déploiement du système de management de la sécurité des aliments.' },
      { step: '04', title: 'Certification', desc: 'Accompagnement lors de l\'audit de certification par l\'organisme choisi.' },
    ],
  },
  {
    slug: 'gouvernement-echanges',
    title: 'Gouvernement & Facilitation des échanges',
    icon: '🌐',
    color: 'from-indigo-400 to-blue-600',
    colorPale: 'from-indigo-50 to-blue-50',
    iconColor: 'text-indigo-600',
    tag: 'ISO 9001 · ISO 37001 · AEO',
    description:
      "Pour les organismes publics et les structures facilitant le commerce international, CERTIZEN déploie des systèmes de management de la qualité et d'anti-corruption conformes aux standards internationaux.",
    descriptionLong: [
      "Les organismes publics et les opérateurs du commerce international font face à des exigences croissantes de transparence, d'efficacité et de conformité. La certification ISO 9001 et le statut AEO sont des leviers de performance reconnus.",
      "CERTIZEN accompagne les administrations et opérateurs économiques dans leur démarche de certification, en tenant compte des spécificités du secteur public.",
    ],
    certifications: ['ISO 9001', 'ISO 37001 Anti-corruption', 'AEO (Opérateur Economique Agréé)', 'ISO 37301'],
    avantages: [
      "Amélioration mesurable de la qualité des services aux usagers",
      "Transparence et lutte efficace contre la corruption",
      "Facilitation et accélération des échanges commerciaux",
      "Conformité aux conventions et normes internationales",
      "Renforcement de la crédibilité institutionnelle",
    ],
    process: [
      { step: '01', title: 'Cartographie des processus', desc: 'Identification et description des processus clés de l\'organisation.' },
      { step: '02', title: 'Politique qualité', desc: 'Définition des objectifs et indicateurs de performance.' },
      { step: '03', title: 'Formation des agents', desc: 'Sensibilisation du personnel aux exigences et bonnes pratiques.' },
      { step: '04', title: 'Certification', desc: 'Audit de certification et suivi de la conformité.' },
    ],
  },
  {
    slug: 'fabrication-industrie',
    title: 'Fabrication & Transformation industrielles',
    icon: '🏭',
    color: 'from-gray-500 to-zinc-700',
    colorPale: 'from-gray-50 to-zinc-50',
    iconColor: 'text-zinc-600',
    tag: 'ISO 9001 · ISO 14001 · ISO 45001',
    description:
      "CERTIZEN aide les industriels à optimiser leurs processus de fabrication, améliorer la qualité de leurs produits et réduire leurs impacts sur l'environnement et la sécurité des travailleurs.",
    descriptionLong: [
      "L'industrie manufacturière est au cœur de l'économie nationale. Face à la compétition internationale, la certification ISO 9001 est devenue un prérequis pour accéder aux grands comptes et à l'export.",
      "CERTIZEN déploie des systèmes de management intégrés (SMI) qui couvrent simultanément la qualité, l'environnement et la sécurité, pour une efficacité maximale.",
    ],
    certifications: ['ISO 9001', 'ISO 14001', 'ISO 45001', 'IATF 16949', 'AS9100'],
    avantages: [
      "Optimisation des processus de production et réduction des gaspillages",
      "Réduction des défauts, non-conformités et coûts de non-qualité",
      "Amélioration de la productivité et des délais de livraison",
      "Accès aux grands comptes exigeant la certification fournisseur",
      "Conformité aux exigences clients et réglementaires",
    ],
    process: [
      { step: '01', title: 'Diagnostic qualité', desc: 'Évaluation des performances actuelles et identification des axes d\'amélioration.' },
      { step: '02', title: 'Cartographie & procédures', desc: 'Documentation des processus de fabrication et contrôle qualité.' },
      { step: '03', title: 'Déploiement & formation', desc: 'Mise en œuvre des nouvelles pratiques et formation du personnel.' },
      { step: '04', title: 'Certification & amélioration', desc: 'Obtention de la certification et plan d\'amélioration continue.' },
    ],
  },
  {
    slug: 'medtech',
    title: 'MedTech',
    icon: '🩺',
    color: 'from-red-400 to-rose-600',
    colorPale: 'from-red-50 to-rose-50',
    iconColor: 'text-red-500',
    tag: 'ISO 13485 · MDR · ISO 14971',
    description:
      "Le secteur des dispositifs médicaux requiert des standards de qualité parmi les plus stricts au monde. CERTIZEN accompagne les fabricants dans la mise en conformité ISO 13485 et les réglementations MDR.",
    descriptionLong: [
      "Les dispositifs médicaux sont soumis aux réglementations les plus exigeantes pour garantir la sécurité des patients. Le Règlement Européen MDR 2017/745 a durci les exigences de mise sur le marché.",
      "CERTIZEN vous guide dans la mise en place de votre Système de Management de la Qualité (SMQ) selon ISO 13485, la gestion des risques selon ISO 14971 et la préparation au marquage CE.",
    ],
    certifications: ['ISO 13485', 'MDR 2017/745', 'ISO 14971', 'IEC 62304', 'IEC 62366'],
    avantages: [
      "Mise sur le marché européen avec marquage CE conforme",
      "Contrôle qualité rigoureux tout au long du cycle de vie du dispositif",
      "Maîtrise des risques liés à la sécurité des patients",
      "Conformité réglementaire internationale (FDA 21 CFR Part 820)",
      "Accès aux marchés les plus exigeants et valorisants",
    ],
    process: [
      { step: '01', title: 'Gap Analysis MDR', desc: 'Évaluation de votre conformité actuelle aux exigences MDR et ISO 13485.' },
      { step: '02', title: 'Gestion des risques', desc: 'Mise en place du processus de gestion des risques selon ISO 14971.' },
      { step: '03', title: 'SMQ & documentation', desc: 'Structure du SMQ, procédures et dossiers techniques.' },
      { step: '04', title: 'Audit de certification', desc: 'Accompagnement lors de l\'audit par l\'organisme notifié.' },
    ],
  },
  {
    slug: 'industrie-miniere',
    title: 'Industrie Minière',
    icon: '⛰️',
    color: 'from-yellow-500 to-amber-700',
    colorPale: 'from-yellow-50 to-amber-50',
    iconColor: 'text-yellow-600',
    tag: 'ISO 45001 · ISO 14001 · IRMA',
    description:
      "L'industrie minière présente des risques spécifiques pour la sécurité et l'environnement. CERTIZEN déploie des systèmes de management intégrés pour protéger les travailleurs et minimiser l'impact environnemental.",
    descriptionLong: [
      "Les mines et carrières sont parmi les environnements de travail les plus dangereux. La réglementation est stricte et les exigences des investisseurs et partenaires internationaux en matière de RSE sont croissantes.",
      "CERTIZEN vous aide à structurer votre système HSE, à réduire les accidents et à obtenir les certifications qui attestent de votre engagement pour la sécurité et l'environnement.",
    ],
    certifications: ['ISO 45001', 'ISO 14001', 'ISO 9001', 'IRMA', 'ICMC'],
    avantages: [
      "Réduction significative des accidents miniers graves et mortels",
      "Conformité aux réglementations environnementales minières",
      "Amélioration des conditions de travail des mineurs",
      "Certification internationale valorisée par les investisseurs",
      "Réduction des risques de passif environnemental",
    ],
    process: [
      { step: '01', title: 'Évaluation des risques', desc: 'Identification des risques spécifiques à l\'activité minière.' },
      { step: '02', title: 'Système HSE intégré', desc: 'Mise en place des procédures de prévention et d\'urgence.' },
      { step: '03', title: 'Formation terrain', desc: 'Formation des opérateurs et responsables sécurité.' },
      { step: '04', title: 'Certification', desc: 'Audit de certification ISO 45001 et ISO 14001.' },
    ],
  },
  {
    slug: 'petrole-gaz-chimie',
    title: 'Pétrole, Gaz & Produits Chimiques',
    icon: '🔥',
    color: 'from-orange-500 to-red-700',
    colorPale: 'from-orange-50 to-red-50',
    iconColor: 'text-orange-600',
    tag: 'ISO 45001 · ISO 14001 · REACH · PSM',
    description:
      "Pour les entreprises du secteur Oil & Gas et chimique, CERTIZEN met en place des systèmes rigoureux de gestion des risques industriels, conformes aux normes internationales les plus exigeantes.",
    descriptionLong: [
      "Le secteur pétrolier, gazier et chimique présente des risques industriels majeurs (explosion, pollution, accidents graves). Les normes internationales imposent des systèmes de management robustes.",
      "CERTIZEN vous accompagne dans la mise en conformité aux normes HSE, la gestion des substances dangereuses (REACH) et la prévention des accidents industriels majeurs.",
    ],
    certifications: ['ISO 45001', 'ISO 14001', 'ISO 9001', 'REACH', 'API Q1/Q2', 'PSM'],
    avantages: [
      "Prévention des accidents industriels majeurs (explosion, fuite, incendie)",
      "Conformité aux réglementations REACH sur les substances chimiques",
      "Gestion rigoureuse des risques environnementaux",
      "Certification pour répondre aux exigences des opérateurs internationaux",
      "Réduction des incidents et arrêts de production",
    ],
    process: [
      { step: '01', title: 'Analyse des risques majeurs', desc: 'Identification des scénarios d\'accidents majeurs et mesures de prévention.' },
      { step: '02', title: 'Système HSE', desc: 'Déploiement des procédures et systèmes de management des risques.' },
      { step: '03', title: 'Formation & exercices', desc: 'Formation du personnel et exercices de simulation d\'urgence.' },
      { step: '04', title: 'Certification', desc: 'Audit de certification et revue périodique du système.' },
    ],
  },
  {
    slug: 'pharma',
    title: 'Pharma',
    icon: '💊',
    color: 'from-cyan-400 to-blue-600',
    colorPale: 'from-cyan-50 to-blue-50',
    iconColor: 'text-cyan-600',
    tag: 'BPF/GMP · ICH Q10 · GDP',
    description:
      "L'industrie pharmaceutique est soumise aux réglementations les plus strictes. CERTIZEN accompagne les laboratoires et façonniers dans la mise en conformité BPF (Bonnes Pratiques de Fabrication) et les standards ICH.",
    descriptionLong: [
      "La qualité et la sécurité des médicaments sont des enjeux vitaux pour les patients. Les autorités de santé (FDA, EMA, AMIP) imposent des exigences très strictes aux fabricants pharmaceutiques.",
      "CERTIZEN vous aide à mettre en place votre système qualité pharmaceutique selon ICH Q10, à valider vos procédés et à préparer vos inspections réglementaires.",
    ],
    certifications: ['BPF / GMP ICH Q7', 'ISO 9001', 'ICH Q10', 'GDP (Distribution)', 'ISO 15189'],
    avantages: [
      "Conformité aux inspections des autorités (FDA, EMA, AMIP, DMP)",
      "Maîtrise de la qualité des médicaments tout au long du cycle de vie",
      "Validation complète des procédés, équipements et locaux",
      "Accès aux marchés pharmaceutiques réglementés",
      "Réduction des risques de rappels et non-conformités",
    ],
    process: [
      { step: '01', title: 'Gap Analysis GMP', desc: 'Évaluation de votre conformité aux BPF et identification des écarts.' },
      { step: '02', title: 'Système qualité', desc: 'Mise en place de l\'ICH Q10 et des procédures GMP.' },
      { step: '03', title: 'Validation', desc: 'Validation des procédés, équipements, méthodes analytiques.' },
      { step: '04', title: 'Préparation inspection', desc: 'Préparation aux inspections réglementaires et audit interne GMP.' },
    ],
  },
  {
    slug: 'energie',
    title: 'Énergie',
    icon: '⚡',
    color: 'from-yellow-400 to-lime-600',
    colorPale: 'from-yellow-50 to-lime-50',
    iconColor: 'text-yellow-500',
    tag: 'ISO 50001 · ISO 14001 · IEC 62443',
    description:
      "Face aux enjeux énergétiques et climatiques, CERTIZEN aide les entreprises du secteur énergétique à optimiser leur consommation, réduire leur empreinte carbone et se conformer aux réglementations environnementales.",
    descriptionLong: [
      "La transition énergétique est une réalité que les entreprises doivent intégrer dans leur stratégie. ISO 50001 offre un cadre structuré pour améliorer l'efficacité énergétique de manière continue.",
      "CERTIZEN vous accompagne dans la mise en place de votre Système de Management de l'Énergie (SMÉ), la définition de vos objectifs de réduction et la certification ISO 50001.",
    ],
    certifications: ['ISO 50001', 'ISO 14001', 'ISO 45001', 'IEC 62443', 'Label Énergie+'],
    avantages: [
      "Réduction mesurable de la consommation énergétique (10 à 30%)",
      "Conformité aux objectifs climatiques nationaux et internationaux",
      "Réduction des coûts énergétiques et amélioration de la compétitivité",
      "Image d'entreprise engagée dans la transition énergétique",
      "Certification pour les énergies renouvelables et projets verts",
    ],
    process: [
      { step: '01', title: 'Revue énergétique', desc: 'Audit de votre consommation énergétique et identification des postes clés.' },
      { step: '02', title: 'Plan d\'efficacité', desc: 'Définition des objectifs et projets d\'amélioration énergétique.' },
      { step: '03', title: 'Déploiement SMÉ', desc: 'Mise en place du système de management de l\'énergie.' },
      { step: '04', title: 'Certification ISO 50001', desc: 'Audit de certification et suivi des performances énergétiques.' },
    ],
  },
  {
    slug: 'transport',
    title: 'Transport',
    icon: '🚛',
    color: 'from-sky-400 to-blue-600',
    colorPale: 'from-sky-50 to-blue-50',
    iconColor: 'text-sky-600',
    tag: 'ISO 9001 · ISO 39001 · AEO',
    description:
      "Le secteur des transports est essentiel à l'économie nationale. CERTIZEN accompagne les opérateurs de transport dans l'amélioration de la sécurité routière, la gestion de la flotte et la conformité aux normes qualité.",
    descriptionLong: [
      "Le transport routier, maritime et aérien sont soumis à des réglementations strictes en matière de sécurité, qualité et conformité douanière. La certification est un avantage compétitif majeur.",
      "CERTIZEN vous aide à structurer votre système de management du transport, réduire les accidents, optimiser votre logistique et obtenir les certifications qui valorisent votre entreprise.",
    ],
    certifications: ['ISO 9001', 'ISO 39001 (Sécurité routière)', 'ISO 45001', 'AEO (Opérateur Agréé)', 'TAPA FSR'],
    avantages: [
      "Réduction significative des accidents et incidents de transport",
      "Optimisation de la logistique, des délais et des coûts",
      "Statut AEO pour la facilitation douanière et réduction des contrôles",
      "Amélioration de la ponctualité et de la fiabilité des livraisons",
      "Avantage concurrentiel sur les appels d'offres logistiques",
    ],
    process: [
      { step: '01', title: 'Analyse du risque transport', desc: 'Évaluation des risques routiers, accidents et incidents.' },
      { step: '02', title: 'Système de management', desc: 'Mise en place des procédures qualité et sécurité transport.' },
      { step: '03', title: 'Formation conducteurs', desc: 'Sensibilisation aux bonnes pratiques de conduite et sécurité.' },
      { step: '04', title: 'Certification', desc: 'Accompagnement lors de l\'audit ISO 9001, ISO 39001 ou AEO.' },
    ],
  },
]

export type Secteur = typeof secteurs[0]

export function getSecteurBySlug(slug: string): Secteur | undefined {
  return secteurs.find((s) => s.slug === slug)
}
